### PR TITLE
Reduce  Locale file

### PR DESCRIPTION
**Pull request by PlexPt**
Change the locale generation rules.
Reduced from 18,000 lines to 40 lines.

Fully tested, I  tested in sandbox mode and editer mode. 
you can  test yourself again before releasing.

### CODE REVIEW

**Comment by PlexPt** [comment]
https://github.com/veden/Rampant/pull/68#issuecomment-1002202240

**Comment by PlexPt** [comment]
After the test is stable, you can delete the extra lines in the file

**Comment by PlexPt** [comment]
tested

**Comment by PlexPt** [comment]
oops

**Comment by veden** [comment]
Thanks for the refactors, they seem to be quite the improvement for localization.
What is the oops for?

**Comment by veden** [comment]
it looks like some names are still missing, I'm fixing them for the english locale.

**Comment by PlexPt** [comment]
missing what？
I see all entities are not missing

**Comment by veden** [comment]
acid pools
proxy entities

**Pull request merged**
