### PR TITLE
Add full Chinese locale

### PR DESCRIPTION
**Pull request by PlexPt**

### CODE REVIEW

**Comment by veden** [comment]
Thanks again for contributing

**Comment by PlexPt** [comment]
I don't think it is necessary to configure so many entries, just simply splice them instead.

**Comment by PlexPt** [comment]
I don't think there need to be too many specific terms, basic terms can be combined into complex ones.

**Comment by veden** [comment]
You are probably correct, the reason for the current state is that when I initially did the logic for naming I didn't know as much about modding in Factorio.
At this point I haven't gone back to refactor the logic.
If you are wanting to make a patch for the splicing that would be awesome and much appreciated.

**Comment by veden** [comment]
https://github.com/veden/Rampant/blob/master/prototypes/UnitClasses.lua
Is what was used to generate the initial locale

**Comment by PlexPt** [comment]
I would like to try, If I have time.
Many thanks.

---Original---
From: ***@***.***&gt;
Date: Wed, Dec 29, 2021 01:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [veden/Rampant] Add full Chinese locale (PR #68)




 
https://github.com/veden/Rampant/blob/master/prototypes/UnitClasses.lua
 Is what was used to generate the initial locale

**Comment by PlexPt** [comment]
https://github.com/veden/Rampant/pull/83

**Comment by PlexPt** [comment]
> 您可能是对的，当前状态的原因是，当我最初进行命名逻辑时，我对异星工厂中的改装知之甚少。 在这一点上，我还没有回去重构逻辑。 如果您想为拼接制作一个补丁，那将非常棒且非常感谢。

https://github.com/veden/Rampant/pull/83

**Pull request merged**
